### ISSUE TITLE
Please Help me On Create  A Demo

### ISSUE THREAD

**Issue by miaozhang** [jcabi/jcabi-aspects#181] opened 2015-09-10 06:43 UTC
I want to create a demo Maven project and use  `@Timeable(limit = 1, unit = TimeUnit.SECONDS) `

i have been follow the exact instructions the listed in http://aspects.jcabi.com/ .

However, Nothing happened regardless run from IDE or  From Maven Jar File. The Annotation been totoally ignored.

If there is some tricky things need to do inorder to see the effect, please tell me. And please give me some detail instructions as i am Maven noob!

**Comment by dmarkov** [comment] 2015-09-14 07:43
@yegor256 please dispatch this issue

**Comment by yegor256** [comment] 2015-09-26 21:49
@miaozhang this seems to be a duplicate of #180

**Closed by yegor256** 2015-09-26 21:49 UTC
